try a single test

diff --git a/.github/workflows/build-ubuntu-macos.yml b/.github/workflows/build-ubuntu-macos.yml
--- a/.github/workflows/build-ubuntu-macos.yml
+++ b/.github/workflows/build-ubuntu-macos.yml
@@ -48,19 +48,21 @@ jobs:
 
       - name: configure for ubuntu
         if: startsWith(matrix.os, 'ubuntu')
+        # it seems that -fsanitize=address and -fsanitize=memory fail under catch on Ubuntu
         run: |
-          ./configure CFLAGS='-g -O0 -fprofile-arcs -ftest-coverage' CXXFLAGS='-g -O0 -fprofile-arcs -ftest-coverage -fsanitize=address -fno-omit-frame-pointer' LIBS='-lgcov'
+          ./configure CXXFLAGS='-g -O0 -fprofile-arcs -ftest-coverage ' LIBS='-lgcov'
 
       - name: configure for macOS
         if: startsWith(matrix.os, 'macos')
+        #
         run: |
-          ./configure
+          ./configure CXXFLAGS='-g -O0 -fsanitize=address -fsanitize=memory -fno-omit-frame-pointer' LIBS='-lgcov'
 
       - name: make check
         run: |
           make test_be13_api
-          ./test_be13_api run      # just run a single test
-          #make check  || (for fn in test*.log ; do echo ""; echo $fn ; cat $fn ; done; exit 1)
+          ./test_be13_api
+          make check  || (for fn in test*.log ; do echo ""; echo $fn ; cat $fn ; done; exit 1)
 
       - uses: ammaraskar/gcc-problem-matcher@0.1
         name: GCC Problem Matcher
